### ISSUE TITLE
0xSpearmint1 - the `creator` role can set a malicious drawManager

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-pooltogether-judging#3]
0xSpearmint1

high

# the `creator` role can set a malicious drawManager

## Summary
the `creator` role can set a malicious drawManager 

## Vulnerability Detail
The protocol clearly states the following
>The only permissioned role in the codebase is the Prize Vault owner. 

There exists a role in the `prizePool` contract called `creator`. The role is set in the constructor like this

```solidity
constructor(
    ConstructorParams memory params
  )
  ...
  ...
  creator = params.creator;
  ...

```

Only the `creator` can call the important `setDrawManager()` function to set the DrawManager contract

```solidity
function setDrawManager(address _drawManager) external {
    if (msg.sender != creator) { //@audit the creator can set a malicious drawManager
      revert OnlyCreator();
    }
    if (drawManager != address(0)) {
      revert DrawManagerAlreadySet();
    }
    drawManager = _drawManager;

    emit SetDrawManager(_drawManager);
  }
```

The vulnerability is in setting a malicious DrawManager contract. This can have a variety of impacts depending on what the attacker wants:
1. The DrawManager contract does not interact with Witnet to get random numbers, instead it will provide random numbers from the attacker's source to ensure they always win prizes

2. DrawManager's crucial functions are set to revert, this completely DOS's the protocol

## Impact
attacker uses a malicious DrawManager to unfairly win prizes

complete DOS of the protocol 

## Code Snippet
https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-prize-pool/src/PrizePool.sol#L392-L402

## Tool used

Manual Review

## Recommendation
The protocol should deploy the DrawManager themselves and set it directly in the prizePool constructor 

Duplicate of #60

**Comment by 0xSpearmint1** [comment]
This is a valid high severity issue

The protocol clearly states in the README
>The only permissioned role in the codebase is the Prize Vault owner. 

The **root cause** of the issue is that the `creator` role can set a malicious implementation of the DrawManager contract.

For example the malicious implementation will not interact with Witnet to get random numbers, instead it will provide random numbers from the attacker's source to ensure they always win prizes.

The **main impact** is that the attacker could manipulate the winning random number to favour themselves

**Comment by 0xjuaan** [comment]
Escalate
On behalf of @0xspearmint1

**Comment by sherlock-admin3** [comment]
> Escalate
> On behalf of @0xspearmint1 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
The following can also be interpreted in a way in which the prize vault owner is the only **restricted permissioned role**. It makes little sense for the pooltogethers protocol admins (the ones deploying the contract and setting the draw manager) to be malicious and brick the whole protocol.

> The only permissioned role in the codebase is the Prize Vault owner. They can create new Prize Vaults permissionlessly. As explained above, we do not expect to gatekeep the creation of new prize vaults. However, we do want the logic of the prize vault to be sound for good actors.

**Comment by 0xSpearmint1** [comment]
Why do you need to interpret the README? It is clear that the ONLY permissioned role in the codebase is the Prize Vault owner.

There is no proof that the `creator` role is the protocol admin. 

If the role is trusted it should have been included in the README

**Comment by nevillehuang** [comment]
@0xspearmint1 I can understand your point of view, just makes no sense to me that the `DrawManager` being the core logic to allow starting and drawing of rounds will be set by any other role other than the admin.

I will leave it to HOJ to consider, but my understanding is it corresponds to the following sherlock rule:

> Direct Protocol Owner/Admin rug pulls. If a protocol specifically mentions the restrictions imposed on the owner/admin, issues describing an attack that results in bypassing these restrictions can be considered valid. Please note that these restrictions must be explicitly described by the protocol and will be considered case by case.
Admin functions are assumed to be used properly, unless a list of requirements is listed and it's incomplete or if there is no scenario where a permissioned funtion can be used properly.

**Comment by 0x73696d616f** [comment]
This was not mentioned in this issue I think, but the malicious contract can only be set in the beginning.

**Comment by WangSecurity** [comment]
> That being said, prize vaults can be created by anyone. We understand that a bad actor could create a vault and steal all of the yield or prizes, or even use a malicious yield source. We do not expect to prevent that scenario

As I see from this part of the README, the protocol doesn't want to prevent malicious actors from creating prize vault and steal all the prizes. Hence, it's an acceptable behaviour based on README.

Planning to reject the escalation and invalidate the issue.

**Comment by 0xSpearmint1** [comment]
@WangSecurity This issue is not related to prize vault owners. The creator role is a totally different role and their sole purpose is to set the draw manager.

The point they made in the README is about a prizeVault owner making a malicious vault to steal ONLY that vault's yield

My issue is about the creator setting a malicious draw manager to steal all the prizes of every vault

How is this an acceptable risk?

If you need more information to understand the role let me know.

**Comment by InfectedIsm** [comment]
The Prize Pool is deployed by admins, and creator is a parameter set during construction, by admins.
As said by @nevillehuang, the Draw Manager is a core contract, as it is mandatory for the Prize Pool to be able to draw and distribute prizes, so it is expected to be set as soon as the Prize Pool is deployed for it to simply function.
Finally, it can only be set once.

_Now, even if the creator was malicious (which is very unlikely as it is configured and chosen by admins and has only one 'initialization' action), he could only act before anything even start, and would have an impact after a first draw finishes, which lets plenty of time for admins to notice the draw manager address is incorrect, thus shutting down the Prize Pool and redeploy a new one with a correct Draw Manager._

**Comment by WangSecurity** [comment]
I see that the `creator` is the parameter set in the constructor and it's not the deployer necessarily. Still the Prize Pool contract does't have any owner/admin functions and as I understand the creator is the one who **creates** the Prize Pool and it can be anyone. Hence, I believe the line from README I quoted above should apply to the creator role as well. I see that the documentation says the `creator` role sets the Draw Manager, so it doesn't override what is said above.

Secondly, irrelevant of the above, the README clearly says "We understand that a bad actor could create a vault and steal all of the yield or prizes, or even use a malicious yield source. We do not expect to prevent that scenario." Hence, it's an acceptable risk, since the protocol doesn't expect to prevent it.

Planning to reject the escalation and leave the issue as it is.

**Comment by 0xSpearmint1** [comment]
@WangSecurity There is a huge misunderstanding of the protocol and the README statement here.

The line from the README does not apply to the creator role. There is only 1 creator since the protocol has 1 prizepool and drawManager vs unlimited number of vaults and vault owners

To your second point. "We understand that a bad actor could create a vault and steal all of the yield or prizes, or even use a malicious yield source. We do not expect to prevent that scenario." This is referring to a Vault owner stealing the yield of their vault they created. This is very different from the creator stealing the prizes of every single vault in existence.

**Comment by WangSecurity** [comment]
Firstly, let’s clarify, by saying “vault” you mean “yield vault” and prize pool is obviously “prize pool”. Let’s refer to them as YV and PP.

Secondly, please tell me then what is the difference between PP owner and PP creator. I don’t see any owner/admin functions in the PP contract, but a creator function. I believe it’s fair to assume that the README refers to the creator role, when saying “anyone can **create** PP”.

Thirdly, I want to emphasise that I wasn’t referring to YV in the previous messages, excuse me if it was confusing. And the README talks about PL, not YV, cause it says **prize vaults** (I believe it means prize pools) can be created by anyone, if not please correct me (I mean say how it is exactly with evidence and not just stating it’s wrong).

> This is referring to a Vault owner stealing the yield of their vault they created. This is very different from the creator stealing the prizes of every single vault in existence.

The README clearly says “steal all of the yield or **prizes**”. So the README refers to stealing both, not only yield.

So please tell me what is the difference between prize vault and prize pool? Why creator is considered malicious in that case?

**Comment by WangSecurity** [comment]
Excuse me for mixing Prize Vault and Prize Pool and making a wrong comment.

Indeed, the README doesn't mention the creator role at all, hence, we cannot assume it's restricted. Firstly, because it's set by the protocol team itself and we should assume they won't set a malicious address here. Secondly, the following about restricted admins applies I believe:

> As mentioned in the standards observed, in the case of a restricted admin, the restriction must be clearly mentioned for any issue in this category to be considered valid

I don't see any restrictions for this role mentioned, except that it's the only one able to set Draw Manager contract and it's what the protocol does.

Hence, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Duplicate of #60

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xjuaan](https://github.com/sherlock-audit/2024-05-pooltogether-judging/issues/3/#issuecomment-2180009855): rejected
