### ISSUE TITLE
0xSpearmint1 - When a prizeVault owner changes the `yieldFeePercentage` it applies to all the yield accrued till this point leading to unfair losses to users

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-pooltogether-judging#5]
0xSpearmint1

high

# When a prizeVault owner changes the `yieldFeePercentage` it applies to all the yield accrued till this point leading to unfair losses to users

## Summary
When a prizeVault owner changes the `yieldFeePercentage` it applies to all the yield accrued till this point leading to unfair losses to users

## Vulnerability Detail
When a prizeVault owner changes the `yieldFeePercentage` it will apply the new `yieldFeePercentage` for yield that was accrued before the change.

This is unfair since users deposited to the pool knowing the vault had a certain lower `yieldFeePercentage`. The users have experienced a loss as the yield was generated when the `yieldFeePercentage` was lower, but it is accrued using a `yieldFeePercentage` that is higher. 

To be clear this does not involve a malicious prizeVault owner, changing the `yieldFeePercentage` is something any owner may do for whatever reason.

## Impact
Users will have a lower % chance of winning a draw than what they expected when they deposited to the vault

## Code Snippet
https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-vault/src/PrizeVault.sol#L1073-L1079

## Tool used

Manual Review

## Recommendation
Implement a system where after the `yieldFeePercentage` is changed, a final liquidation of all existing yield occurs using the previous `yieldFeePercentage`, and then the  `yieldFeePercentage` is updated to the new value for future yield liquidations.

or

Implement a timelock system so that once `yieldFeePercentage` is changed, there is ample tiem for a final liqudiation with the previous `yieldFeePercentage`. after the set time `yieldFeePercentage` is updated to the new value.

**Comment by 0xSpearmint1** [comment]
This is a valid medium severity issue

**Root cause:** Updating `yieldFeePercentage` will apply the new `yieldFeePercentage` RETROACTIVELY to all yield generated till that point

**Impact:** When `yieldFeePercentage` is increased, all depositors will have a lower chance of winning a draw 

**Fix:** After `yieldFeePercentage` is changed, the next liqudiation must use the PREVIOUS `yieldFeePercentage` to liquidate the existing yield, this way the depositors are not impacted negatively. The new `yieldFeePercentage` will now apply to yield generated from that point on.

**Note:** It is wrong to apply the NEW `yieldFeePercentage` to OLD yield

**Comment by 0xjuaan** [comment]
Escalate
On behalf of @0xspearmint1

**Comment by sherlock-admin3** [comment]
> Escalate
> On behalf of @0xspearmint1

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
Per contest details, prize vault owners are trusted to manage yield, so escalation should be rejected

> We understand that a bad actor could create a vault and steal all of the yield or prizes, or even use a malicious yield source. We do not expect to prevent that scenario.

**Comment by 0xSpearmint1** [comment]
Just want to make it clear that this issue does not involve a bad actor prize vault owner. I even mentioned this in my original issue.

This issue affects honest prizeVault owners that just wanted to change the `yieldFeePercentage`. 

The protocol stated in the README
>we do want the logic of the prize vault to be sound for good actors.

The logic of using a NEW `yieldFeePercentage` on OLD yield is not sound because it negatively affects all depositors.

**Comment by WangSecurity** [comment]
I see that this indeed can happen with both trusted and untrusted prize vault owners. In case of untrusted it's obviously invalid based on README, but in case of trusted, I believe it's design decision to apply `yieldFeePercentage` in that way, secondly, I believe the following should apply in case of an honest owner:

> An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue.

Hence, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xjuaan](https://github.com/sherlock-audit/2024-05-pooltogether-judging/issues/5/#issuecomment-2180234593): rejected
