### ISSUE TITLE
0xSpearmint1 - The `maxDeposit()` function is not ERC4626 compliant

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-pooltogether-judging#9]
0xSpearmint1

medium

# The `maxDeposit()` function is not ERC4626 compliant

## Summary
The `maxDeposit()` function is not ERC4626 compliant

## Vulnerability Detail
The protocol has clearly stated the following
>PrizeVaults are expected to strictly comply with the ERC4626 standard.

According to the official [ERC-4626](https://eips.ethereum.org/EIPS/eip-4626) standard, the following must hold for the `maxDeposit()` function
>MUST return the maximum amount of assets deposit would allow to be deposited for receiver and not cause a revert

The problem is that the `maxDeposit()` function uses `yieldVault.maxDeposit(address(this))` to determine maximum deposit amount

BUT the `_depositAndMint` function uses `yieldVault.mint(_yieldVaultShares, address(this))`

If the `yieldVault.mint()` function has a lower limit than `yieldVault.deposit()`, then depositing the value returned from `maxDeposit()` will revert.

## Impact
There may be issues related to vault integration 

## Code Snippet
https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-vault/src/PrizeVault.sol#L383

## Tool used

Manual Review

## Recommendation
Redesign the function so that it is compliant.

or

The protocol should analyze if this non compliance poses a big risk, if not just let it be and acknowledge the function is not ERC4626 compliant.

**Comment by 0xSpearmint1** [comment]
This is a valid medium severity issue

Let me illustrate with an example to make it clear

A yieldVault can implement a mint() function with a limit of 100 tokens AND a deposit() function with a limit of 200 tokens

therefore `yieldVault.maxMint(address(this))` = 100 tokens
and `yieldVault.maxDeposit(address(this))` = 200 tokens 

Calling `maxDeposit()` on the prizeVault will return 200 tokens because it uses `yieldVault.maxDeposit(address(this))`

If a user tries to deposit 200 tokens to the prizeVault it will revert because the deposit function uses `yieldVault.mint()` which is limited to 100 tokens

**NOTE** The described yieldVault is compliant with ERC-4626

If this is a known issue it should have been documented in the README under 
>Please list any known issues/acceptable risks that should not result in a valid finding.

**Comment by 0xjuaan** [comment]
Escalate
On behalf of @0xspearmint1

**Comment by sherlock-admin3** [comment]
> Escalate
> On behalf of @0xspearmint1

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ghost** [comment]
This is Dupe of #134 @nevillehuang

**Comment by nevillehuang** [comment]
I believe issues #134 duplicates and this issue should be invalid, given it depends on OOS yieldvault contract logic. 

It was also noted as a won't fix finding in C4 finding [here](https://code4rena.com/reports/2024-03-pooltogether#m-03-maxdeposit-uses-yieldvaultmaxdeposit-but-_depositandmint-uses-yieldvaultmint)

**Comment by 0xSpearmint1** [comment]
This is not a duplicate of #134 

The root cause of #134  is related to lossy deposits reverting which is well documented [here](https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-vault/src/PrizeVault.sol#L112-L113). 

My issue is due to `maxDeposit()` function using `yieldVault.maxDeposit(address(this))` BUT `_depositAndMint` function uses `yieldVault.mint(_yieldVaultShares, address(this))` leading to reverts.

The protocol stated in the README
>PrizeVaults are expected to strictly comply with the ERC4626 standard.

My issue clearly shows how the protocol is NOT ERC4626 compliant due to a NON COMPLIANT `MaxDeposit ` function. 

If this was a known issue it should have been documented under the README, which it was not.

**Comment by WangSecurity** [comment]
Firstly, this issue is fully dependant on YieldVault implementation, and in the contest repository we have only mocks of such (correct me if wrong). Moreover, they're outside of scope.

Secondly, the fact that `_depositAndMint` doesn't use `maxDeposit` it doesn't necessarily contradict the ERC4626 Standard. 

Thirdly, based on README, the "trustworthy ERC4626 yield source" will be used, which means we should assume it should be fully compliant.

Hence, based on the reasons stated above, but mainly the fact that `yieldVault::mint` and `yieldVault::deposit` functions are out of scope (correct me if wrong here), this issue should remain low/info.

Planning to reject the escalation and leave the issue as it is.

**Comment by 0xSpearmint1** [comment]
@WangSecurity The yieldVault I described is fully compliant with ERC 4626

The `yieldVault::mint` and `yieldVault::deposit` functions are obviously OOS. BUT the root cause of the issue is in `maxDeposit` returning a value that will revert when calling `deposit`, which it should never do. 

It should never revert according to ERC 4626 and I have clearly shown a case where it will revert when integrating with a yieldVault that IS 100% 4626 compliant.

**Comment by InfectedIsm** [comment]
This is the exact same issue that was sponsor acknowledged from [C4 contest 03-2024 M-03](https://github.com/code-423n4/2024-03-pooltogether-findings/issues/335)
This audit is part of the previous audit listed in the README : 

> Please provide links to previous audits (if any).
> 
> https://code4rena.com/reports/2024-03-pooltogether
> https://0xmacro.com/library/audits/pooltogether-1
> https://code4rena.com/reports/2023-08-pooltogether
> https://code4rena.com/reports/2023-07-pooltogether
> https://code4rena.com/reports/2022-12-pooltogether

**Comment by WangSecurity** [comment]
Firstly, as pointed out above correctly, it’s already a known issue.

Secondly, this issue depends on `yieldVault.mint` and `yieldVault.deposit` having different limits. The report itself says “if” they’re different. Hence, I believe it’s out of scope, cause any of these functions may call maxDeposit on the prize vault.

The decision remains the same, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xjuaan](https://github.com/sherlock-audit/2024-05-pooltogether-judging/issues/9/#issuecomment-2180236554): rejected
